'use client';

import { useState } from 'react';
import { Chip } from "@mui/material";
import {
  Stack,
  Surface,
  Text,
  IconButton,
  Input,
  Spinner,
} from '@/components/ui';
import { colors, radii, shadows, fontSize } from '@/components/ui/tokens';
import {
  AutoAwesomeIcon,
  ArrowUpwardIcon,
  MessageSquareIcon,
} from '@/components/ui/icons';
import { useStudio } from '@/contexts/StudioContext';

interface ChatOverlayProps {
  onSendMessage: (message: string) => void;
}

export default function ChatOverlay({ onSendMessage }: ChatOverlayProps) {
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { activeSessionId, chatSessions } = useStudio();
  const activeSession = chatSessions.find(s => s.id === activeSessionId);

  const handleSend = async () => {
    if (input.trim() && !isLoading) {
      setIsLoading(true);
      try {
        await onSendMessage(input);
        setInput('');
      } finally {
        setIsLoading(false);
      }
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div
      style={{
        position: 'absolute',
        bottom: 24,
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 1000,
        width: '100%',
        maxWidth: 600,
        paddingLeft: 16,
        paddingRight: 16,
      }}
    >
      {/* Main Input Container with Purple Border */}
      <Surface
        elevation={2}
        radius="lg"
        sx={{
          border: '1px solid rgba(139, 92, 246, 0.3)',
          p: 2.5,
        }}
      >
        {/* Context Label and Chips */}
        {activeSessionId && activeSession && (
          <Stack direction="row" align="center" gap={1} sx={{ mb: 2 }}>
            <Text
              variant="overline"
              color="secondary"
              sx={{ letterSpacing: '0.5px' }}
            >
              CONTEXT:
            </Text>
            <Chip
              label={activeSession.title.length > 25 ? activeSession.title.substring(0, 25) + '...' : activeSession.title}
              icon={<MessageSquareIcon size={12} sx={{ color: 'rgba(139, 92, 246, 0.8)' }} />}
              size="small"
              sx={{
                bgcolor: 'rgba(139, 92, 246, 0.1)',
                color: 'rgba(139, 92, 246, 0.9)',
                border: 'none',
                height: 24,
                fontSize: fontSize.xs,
                fontWeight: 500,
              }}
            />
          </Stack>
        )}

        {/* Input Field with Sparkle Icon */}
        <Stack
          direction="row"
          align="center"
          gap={1}
          sx={{
            bgcolor: colors.background.subtle,
            borderRadius: `${radii.lg}px`,
            px: 2,
            py: 1.5,
            border: `1px solid ${colors.border.muted}`,
          }}
        >
          <AutoAwesomeIcon size={18} sx={{ color: 'rgba(139, 92, 246, 0.8)', flexShrink: 0 }} />
          <input
            type="text"
            placeholder="Ask a follow-up question or drag a new resource..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyPress}
            disabled={isLoading}
            style={{
              flex: 1,
              border: 'none',
              outline: 'none',
              background: 'transparent',
              fontSize: fontSize.sm,
              color: colors.text.primary,
            }}
          />
          {isLoading ? (
            <Spinner size="sm" color="primary" />
          ) : (
            <IconButton
              size="sm"
              onClick={handleSend}
              disabled={!input.trim()}
              sx={{
                bgcolor: 'rgba(139, 92, 246, 1)',
                color: '#fff',
                borderRadius: `${radii.md}px`,
                '&:hover': {
                  bgcolor: 'rgba(139, 92, 246, 0.9)',
                },
                '&:disabled': {
                  bgcolor: 'rgba(139, 92, 246, 0.3)',
                  color: 'rgba(255, 255, 255, 0.5)',
                },
              }}
            >
              <ArrowUpwardIcon size={18} />
            </IconButton>
          )}
        </Stack>
      </Surface>

      {/* Status Text */}
      <div style={{ textAlign: 'center', marginTop: 16 }}>
        <Text variant="caption" color="secondary" sx={{ fontSize: '0.7rem' }}>
          Thinking Mode Active, • Results are generated by AI.
        </Text>
      </div>
    </div>
  );
}
