import React, { useState } from 'react';
import { Box, Paper, Typography, IconButton, Button, Chip, Modal, Fade, Backdrop } from '@mui/material';
import { CloseIcon, FullscreenIcon, AutoAwesomeIcon, TrendingUpIcon, PeopleIcon, ArrowForwardIcon, ContentCopyIcon, ShareIcon, DockIcon } from '@/components/ui/icons';
import { KeyFinding } from '@/lib/api';

interface SummaryCardProps {
  title: string;
  summary: string;
  keyFindings: KeyFinding[];
  onClose: () => void;
  onDock?: () => void;
  onFullScreen?: () => void;
  onShare?: () => void;
  onCopy?: () => void;
}

export default function SummaryCard({ 
  title, 
  summary, 
  keyFindings,
  onClose,
  onDock,
  onShare,
  onCopy
}: SummaryCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  // Parse summary for "Strategy" vs "Insights" tags if possible, or just hardcode for visual match
  // The design shows specific tags. We'll add them statically or infer.
  
  const handleExpand = () => setIsExpanded(true);
  const handleCloseExpanded = () => setIsExpanded(false);

  return (
    <>
      {/* Compact Card */}
      <Paper
        elevation={0}
        sx={{
          width: 380,
          p: 3,
          borderRadius: 4,
          border: '1px solid',
          borderColor: 'divider',
          bgcolor: 'white',
          boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
          position: 'relative',
          animation: 'slideUp 0.3s ease-out',
          '@keyframes slideUp': {
            from: { opacity: 0, transform: 'translateY(20px)' },
            to: { opacity: 1, transform: 'translateY(0)' }
          }
        }}
      >
        {/* Header */}
        <Box sx={{ display: 'flex', alignItems: 'flex-start', mb: 3 }}>
          {/* Icon */}
          <Box
            sx={{
              width: 40,
              height: 40,
              borderRadius: 3,
              background: 'linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white',
              mr: 2,
              boxShadow: '0 4px 12px rgba(139, 92, 246, 0.3)',
              flexShrink: 0
            }}
          >
            <AutoAwesomeIcon size="md" sx={{ fill: 'currentColor' }} />
          </Box>

          {/* Title Info */}
          <Box sx={{ flex: 1, minWidth: 0 }}>
            <Typography variant="subtitle1" fontWeight={700} sx={{ lineHeight: 1.2, mb: 0.5 }} noWrap>
              {title}
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
              <Box component="span" sx={{ width: 6, height: 6, borderRadius: '50%', bgcolor: '#4ADE80' }} />
              Generated by Weaver AI
            </Typography>
          </Box>

          {/* Actions */}
          <Box sx={{ display: 'flex', gap: 0.5, flexShrink: 0 }}>
            <IconButton size="small" onClick={handleExpand} sx={{ color: 'text.secondary' }}>
              <FullscreenMui sx={{ fontSize: 16 }} />
            </IconButton>
            <IconButton size="small" onClick={onClose} sx={{ color: 'text.secondary' }}>
              <CloseIcon size="sm" />
            </IconButton>
          </Box>
        </Box>

        {/* Tags */}
        <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
          <Chip 
            label="STRATEGY" 
            size="small" 
            sx={{ 
              bgcolor: '#EEF2FF', 
              color: '#4F46E5', 
              fontWeight: 600, 
              fontSize: '0.7rem',
              height: 24,
              borderRadius: 1
            }} 
          />
          <Chip 
            label="INSIGHTS" 
            size="small" 
            sx={{ 
              bgcolor: '#F5F3FF', 
              color: '#7C3AED', 
              fontWeight: 600, 
              fontSize: '0.7rem',
              height: 24,
              borderRadius: 1
            }} 
          />
        </Box>

        {/* Content Preview */}
        <Typography 
          variant="body2" 
          color="text.secondary" 
          sx={{ 
            mb: 3, 
            lineHeight: 1.6,
            display: '-webkit-box',
            WebkitLineClamp: 3,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden'
          }}
        >
          {summary}
        </Typography>

        {/* Highlights Box */}
        {keyFindings && keyFindings.length > 0 && (
          <Box sx={{ p: 2, bgcolor: '#F8FAFC', borderRadius: 2, mb: 3 }}>
            {keyFindings.slice(0, 2).map((finding, idx) => (
              <Box key={idx} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5, mb: idx === 0 ? 1.5 : 0 }}>
                <Box sx={{ mt: 0.5 }}>
                  {idx === 0 ? <TrendingUpIcon size="sm" sx={{ color: '#10B981' }} /> : <PeopleMui sx={{ fontSize: 16, color: '#3B82F6' }} />}
                </Box>
                <Typography variant="body2" sx={{ fontSize: '0.85rem' }}>
                  <Box component="span" fontWeight={600}>{finding.label}:</Box> {finding.content}
                </Typography>
              </Box>
            ))}
          </Box>
        )}

        {/* Footer Button */}
        <Button
          fullWidth
          variant="contained"
          onClick={handleExpand}
          sx={{
            bgcolor: '#4F46E5',
            borderRadius: 50,
            textTransform: 'none',
            py: 1,
            boxShadow: '0 4px 12px rgba(79, 70, 229, 0.2)',
            '&:hover': {
              bgcolor: '#4338CA'
            }
          }}
          endIcon={<ArrowForwardIcon size="sm" />}
        >
          Read Full Summary
        </Button>
      </Paper>

      {/* Expanded Modal */}
      <Modal
        open={isExpanded}
        onClose={handleCloseExpanded}
        closeAfterTransition
        slots={{ backdrop: Backdrop }}
        slotProps={{
          backdrop: {
            timeout: 500,
            sx: { bgcolor: 'rgba(255, 255, 255, 0.8)', backdropFilter: 'blur(4px)' }
          },
        }}
      >
        <Fade in={isExpanded}>
          <Box sx={{
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            width: '90%',
            maxWidth: 800,
            maxHeight: '90vh',
            bgcolor: 'background.paper',
            borderRadius: 4,
            boxShadow: 24,
            p: 0,
            outline: 'none',
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column'
          }}>
            {/* Modal Header */}
            <Box sx={{ 
              p: 3, 
              borderBottom: '1px solid', 
              borderColor: 'divider',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              bgcolor: 'rgba(255,255,255,0.8)',
              backdropFilter: 'blur(10px)'
            }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <Box
                  sx={{
                    width: 40,
                    height: 40,
                    borderRadius: 3,
                    background: 'linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'white',
                  }}
                >
                  <AutoAwesomeIcon size="md" sx={{ fill: 'currentColor' }} />
                </Box>
                <Box>
                  <Typography variant="h6" fontWeight={700}>
                    {title}
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    AI Generated Summary
                  </Typography>
                </Box>
              </Box>
              <Box sx={{ display: 'flex', gap: 1 }}>
                {onCopy && (
                  <IconButton onClick={onCopy} title="Copy to clipboard">
                    <ContentCopyIcon size="md" />
                  </IconButton>
                )}
                {onShare && (
                  <IconButton onClick={onShare} title="Share">
                    <ShareIcon size="md" />
                  </IconButton>
                )}
                {onDock && (
                  <IconButton onClick={onDock} title="Dock to board">
                    <DockMui sx={{ fontSize: 20 }} />
                  </IconButton>
                )}
                <IconButton onClick={handleCloseExpanded} title="Close">
                  <CloseIcon size="md" />
                </IconButton>
              </Box>
            </Box>

            {/* Modal Content */}
            <Box sx={{ p: 4, overflowY: 'auto', flex: 1 }}>
              <Typography variant="overline" color="primary" fontWeight={700} sx={{ mb: 1, display: 'block' }}>
                EXECUTIVE SUMMARY
              </Typography>
              <Typography variant="body1" paragraph sx={{ lineHeight: 1.8, color: 'text.secondary', mb: 4 }}>
                {summary}
              </Typography>

              <Typography variant="overline" color="primary" fontWeight={700} sx={{ mb: 2, display: 'block' }}>
                KEY FINDINGS
              </Typography>
              <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 3 }}>
                {keyFindings && keyFindings.map((finding, idx) => (
                  <Paper key={idx} elevation={0} sx={{ p: 2.5, bgcolor: '#F8FAFC', borderRadius: 3, border: '1px solid', borderColor: 'divider' }}>
                    <Typography variant="subtitle2" fontWeight={700} gutterBottom sx={{ color: 'text.primary', display: 'flex', alignItems: 'center', gap: 1 }}>
                      <Box component="span" sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: 'primary.main' }} />
                      {finding.label}
                    </Typography>
                    <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>
                      {finding.content}
                    </Typography>
                  </Paper>
                ))}
              </Box>
            </Box>
          </Box>
        </Fade>
      </Modal>
    </>
  );
}