'use client';

import React, { useState } from 'react';
import { Surface, Stack, Text, IconButton, Button, Chip, Modal } from '@/components/ui';
import { colors, radii, shadows } from '@/components/ui/tokens';
import { CloseIcon, FullscreenIcon, AutoAwesomeIcon, TrendingUpIcon, PeopleIcon, ArrowForwardIcon, ContentCopyIcon, ShareIcon, DockIcon } from '@/components/ui/icons';
import { KeyFinding } from '@/lib/api';

interface SummaryCardProps {
  title: string;
  summary: string;
  keyFindings: KeyFinding[];
  onClose: () => void;
  onDock?: () => void;
  onFullScreen?: () => void;
  onShare?: () => void;
  onCopy?: () => void;
}

export default function SummaryCard({
  title,
  summary,
  keyFindings,
  onClose,
  onDock,
  onShare,
  onCopy
}: SummaryCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  // Parse summary for "Strategy" vs "Insights" tags if possible, or just hardcode for visual match
  // The design shows specific tags. We'll add them statically or infer.

  const handleExpand = () => setIsExpanded(true);
  const handleCloseExpanded = () => setIsExpanded(false);

  return (
    <>
      {/* Compact Card */}
      <Surface
        elevation={0}
        radius="xl"
        bordered
        sx={{
          width: 380,
          p: 3,
          boxShadow: shadows.lg,
          position: 'relative',
          animation: 'slideUp 0.3s ease-out',
          '@keyframes slideUp': {
            from: { opacity: 0, transform: 'translateY(20px)' },
            to: { opacity: 1, transform: 'translateY(0)' }
          }
        }}
      >
        {/* Header */}
        <Stack direction="row" align="start" sx={{ mb: 3 }}>
          {/* Icon */}
          <div
            style={{
              width: 40,
              height: 40,
              borderRadius: radii.lg,
              background: 'linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'white',
              marginRight: 16,
              boxShadow: '0 4px 12px rgba(139, 92, 246, 0.3)',
              flexShrink: 0,
            }}
          >
            <AutoAwesomeIcon size="md" sx={{ fill: 'currentColor' }} />
          </div>

          {/* Title Info */}
          <div style={{ flex: 1, minWidth: 0 }}>
            <Text variant="label" truncate sx={{ lineHeight: 1.2, mb: 0.5 }}>
              {title}
            </Text>
            <Stack direction="row" align="center" gap={0} sx={{ gap: 0.5 }}>
              <div
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: '50%',
                  backgroundColor: colors.success[400],
                }}
              />
              <Text variant="caption" color="secondary">
                Generated by Weaver AI
              </Text>
            </Stack>
          </div>

          {/* Actions */}
          <Stack direction="row" gap={0} sx={{ flexShrink: 0, gap: 0.5 }}>
            <IconButton size="sm" variant="ghost" onClick={handleExpand}>
              <FullscreenIcon size={16} />
            </IconButton>
            <IconButton size="sm" variant="ghost" onClick={onClose}>
              <CloseIcon size="sm" />
            </IconButton>
          </Stack>
        </Stack>

        {/* Tags */}
        <Stack direction="row" gap={1} sx={{ mb: 2 }}>
          <Chip
            label="STRATEGY"
            size="sm"
            color="primary"
            variant="soft"
          />
          <Chip
            label="INSIGHTS"
            size="sm"
            color="primary"
            variant="soft"
          />
        </Stack>

        {/* Content Preview */}
        <Text
          variant="bodySmall"
          color="secondary"
          sx={{
            mb: 3,
            lineHeight: 1.6,
            display: '-webkit-box',
            WebkitLineClamp: 3,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden'
          }}
        >
          {summary}
        </Text>

        {/* Highlights Box */}
        {keyFindings && keyFindings.length > 0 && (
          <div
            style={{
              padding: 16,
              backgroundColor: colors.background.subtle,
              borderRadius: radii.md,
              marginBottom: 24,
            }}
          >
            {keyFindings.slice(0, 2).map((finding, idx) => (
              <Stack key={idx} direction="row" align="start" gap={1} sx={{ mb: idx === 0 ? 1.5 : 0 }}>
                <div style={{ marginTop: 4 }}>
                  {idx === 0 ? <TrendingUpIcon size="sm" sx={{ color: colors.success[500] }} /> : <PeopleIcon size={16} sx={{ color: colors.primary[500] }} />}
                </div>
                <Text variant="bodySmall" sx={{ fontSize: '0.85rem' }}>
                  <span style={{ fontWeight: 600 }}>{finding.label}:</span> {finding.content}
                </Text>
              </Stack>
            ))}
          </div>
        )}

        {/* Footer Button */}
        <Button
          fullWidth
          variant="primary"
          onClick={handleExpand}
          style={{
            borderRadius: 50,
            textTransform: 'none',
            paddingTop: 8, paddingBottom: 8,
            boxShadow: '0 4px 12px rgba(79, 70, 229, 0.2)',
            backgroundColor: '#4F46E5',
          }}
          endIcon={<ArrowForwardIcon size="sm" />}
        >
          Read Full Summary
        </Button>
      </Surface>

      {/* Expanded Modal */}
      {/* Expanded Modal */}
      <Modal
        open={isExpanded}
        onClose={handleCloseExpanded}
        size="lg"
        style={{ padding: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}
      >
        {/* Modal Header */}
        <Stack
          direction="row"
          align="center"
          justify="between"
          sx={{
            p: 3,
            borderBottom: `1px solid ${colors.border.default}`,
            bgcolor: 'rgba(255,255,255,0.8)',
            backdropFilter: 'blur(10px)'
          }}
        >
          <Stack direction="row" align="center" gap={2}>
            <div
              style={{
                width: 40,
                height: 40,
                borderRadius: radii.lg,
                background: 'linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'white',
              }}
            >
              <AutoAwesomeIcon size="md" sx={{ fill: 'currentColor' }} />
            </div>
            <div>
              <Text variant="h6">{title}</Text>
              <Text variant="caption" color="secondary">
                AI Generated Summary
              </Text>
            </div>
          </Stack>
          <Stack direction="row" gap={1}>
            {onCopy && (
              <IconButton size="md" variant="ghost" onClick={onCopy} title="Copy to clipboard">
                <ContentCopyIcon size="md" />
              </IconButton>
            )}
            {onShare && (
              <IconButton size="md" variant="ghost" onClick={onShare} title="Share">
                <ShareIcon size="md" />
              </IconButton>
            )}
            {onDock && (
              <IconButton size="md" variant="ghost" onClick={onDock} title="Dock to board">
                <DockIcon size={20} />
              </IconButton>
            )}
            <IconButton size="md" variant="ghost" onClick={handleCloseExpanded} title="Close">
              <CloseIcon size="md" />
            </IconButton>
          </Stack>
        </Stack>

        {/* Modal Content */}
        <div style={{ padding: 32, overflowY: 'auto', flex: 1 }}>
          <Text variant="overline" color="primary" sx={{ mb: 1, display: 'block', fontWeight: 700 }}>
            EXECUTIVE SUMMARY
          </Text>
          <Text variant="body" color="secondary" sx={{ lineHeight: 1.8, mb: 4 }}>
            {summary}
          </Text>

          <Text variant="overline" color="primary" sx={{ mb: 2, display: 'block', fontWeight: 700 }}>
            KEY FINDINGS
          </Text>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
            {keyFindings && keyFindings.map((finding, idx) => (
              <Surface
                key={idx}
                elevation={0}
                radius="lg"
                bordered
                sx={{ p: 2.5, bgcolor: colors.background.subtle }}
              >
                <Stack direction="row" align="center" gap={1} sx={{ mb: 0.5 }}>
                  <div
                    style={{
                      width: 8,
                      height: 8,
                      borderRadius: '50%',
                      backgroundColor: colors.primary[500],
                    }}
                  />
                  <Text variant="label">{finding.label}</Text>
                </Stack>
                <Text variant="bodySmall" color="secondary" sx={{ lineHeight: 1.6 }}>
                  {finding.content}
                </Text>
              </Surface>
            ))}
          </div>
        </div>
      </Modal>
    </>
  );
}